### ISSUE TITLE
bundle install

### ISSUE THREAD

**Issue by valogopedina** [makersacademy/ruby-kickstart#164]
Hi guys,

I forked the repo and cloned it locally but something wrong with bundle install. 

valentina@osboxes:~$ bundle install
The program 'bundle' is currently not installed. To run 'bundle' please ask your administrator to install the package 'bundler'
valentina@osboxes:~$ gem install bundler
Fetching: bundler-1.11.0.gem (100%)
ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the /var/lib/gems/2.1.0 directory.
valentina@osboxes:~$ sudo gem install bundler
[sudo] password for valentina: 
Fetching: bundler-1.11.0.gem (100%)
Successfully installed bundler-1.11.0
Parsing documentation for bundler-1.11.0
Installing ri documentation for bundler-1.11.0
Done installing documentation for bundler after 6 seconds
1 gem installed

valentina@osboxes:~$ cd ruby-kickstart/
valentina@osboxes:~/ruby-kickstart$ bundle install
Fetching gem metadata from https://rubygems.org/.........
Fetching version metadata from https://rubygems.org/..
Resolving dependencies...
Using rake 10.4.2
Installing mime-types 2.4.3
Installing mini_portile 0.6.2
Installing rack 1.6.0
Using diff-lcs 1.2.5
Installing helloworld 0.0.1
Installing rspec-support 3.2.2 (was 3.1.2)
Installing tilt 1.4.1
Using bundler 1.11.0
Installing nokogiri 1.6.6.2 with native extensions

Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    /usr/bin/ruby2.1 extconf.rb
mkmf.rb can't find header files for ruby at /usr/lib/ruby/include/ruby.h

extconf failed, exit code 1

Gem files will remain installed in /tmp/bundler20151214-3156-1eqy0venokogiri-1.6.6.2/gems/nokogiri-1.6.6.2 for inspection.
Results logged to /tmp/bundler20151214-3156-1eqy0venokogiri-1.6.6.2/extensions/x86_64-linux/2.1.0/nokogiri-1.6.6.2/gem_make.out
Installing rack-test 0.6.3
Installing rack-protection 1.5.3
Installing rspec-core 3.2.3 (was 3.1.7)
Installing rspec-expectations 3.2.1 (was 3.1.2)
Installing rspec-mocks 3.2.1 (was 3.1.3)
An error occurred while installing nokogiri (1.6.6.2), and Bundler cannot
continue.
Make sure that `gem install nokogiri -v '1.6.6.2'` succeeds before bundling.

Anyone knows what's wrong? I'm using UBUNTU

**Comment by valogopedina** [comment]
issue solved! Thanks

**Comment by nikeshashar** [comment]
What was the issue and how did you solve it?

**Comment by valogopedina** [comment]
The issue was concerning nokogiri without which it was impossible to install bundle.  I googled and I found this solution that works in UBUNTU : 
1) gem install nokogiri
2) sudo apt-get install build-essential patch
3) sudo apt-get install ruby-dev zlib1g-dev

Hope this is can be useful for someone else who is using Ubuntu.

**Comment by Jeremy-Barrass** [comment]
Thank you valogopedina!  Your issue definitely helped me. :-)

**Comment by valogopedina** [comment]
Good to know!
