### ISSUE TITLE
Having trouble with ruby-kickstart challenge 1:4

### ISSUE THREAD

**Issue by russellvaughan** [makersacademy/ruby-kickstart#177]
I know there is probably a prettier way to do this but I'm still not sure why this doesn't work.

def grade(num_books, has_read_books)

if num_books < 10 && has_read_books != true
	"D"
	elsif num_books <= 10 && has_read_books == true
		"C"
	elsif num_books (10..20) && has_read_books != true
		"C"
        elsif num_books (10..20) && has_read_books == true
     	"B"
       elsif num_books > 20 && has_read_books != true
		"B"
	else 
		num_books > 20 && has_read_books != true
		"A"
	end

end

**Comment by MarcoCode** [comment]
The problem might be the second statement, where the condition should be < 10 not <= 10.

**Comment by russellvaughan** [comment]
helped by @iryna replaced  "num_books (10..20)" with "num_books>=10 && num_books<=20" and it worked
