### ISSUE TITLE
Problem with pull request

### ISSUE THREAD

**Issue by russellvaughan** [makersacademy/ruby-kickstart#179]
I've noticed I have got this error with my pull request. I'm not sure what it means.. 

https://travis-ci.org/makersacademy/ruby-kickstart/builds/96808466

Can anyone shed any light?

**Comment by ggwc82** [comment]
I'm having this error too. Can see lots of others with the same status, a possible issue with write access?

**Comment by nikeshashar** [comment]
![image](https://cloud.githubusercontent.com/assets/7963753/11791659/f88b60e8-a299-11e5-981e-3295312fba0f.png)

**Comment by nikeshashar** [comment]
Check the logs and it will show you the error :)

**Comment by russellvaughan** [comment]
thanks Nikesh.
