### ISSUE TITLE
File not found error when invoking command rake 1:all solved is true

### ISSUE THREAD

**Issue by jwhekk** [makersacademy/ruby-kickstart#184]
The error I got:
rake 1:1 solved=true
ruby -c '/Users/wim/Projects/ruby-kickstart/session1/solved/1.rb'
ruby: No such file or directory -- /Users/wim/Projects/ruby-kickstart/session1/solved/1.rb (LoadError)
rake aborted!

Directory name is "solved" should be "5-solved", after I changed it, it worked fine. It is on line 64 of the Makefile.

**Comment by nikeshashar** [comment]
@jwhekk - please reopen this issue in the PreCourse repo so others can see it.
