### ISSUE TITLE
I'm really curious why my code doesn't work for 2:1

### ISSUE THREAD

**Issue by russellvaughan** [makersacademy/ruby-kickstart#192]
This is my code:

def sum_difference_product
  a = gets.to_i
  b = gets.to_i
  puts a + b
  puts a - b
  puts a * b
end

this is the solution...

def sum_difference_product
  a , b = gets.split.map { |num| num.to_i }
  puts a + b
  puts a - b
  puts a * b
end

am I not getting the solution? is it just because there is one input in the solution and I have two. I just feel I get to the same result.

**Comment by yyl29** [comment]
i think i ran into the same problem, try print/puts them all in one line like the example, separating by \n's

**Comment by russellvaughan** [comment]
i get it now!
