### ISSUE TITLE
Help with 1:7

### ISSUE THREAD

**Issue by frazerWatson** [makersacademy/ruby-kickstart#199]
After spending the whole day on this problem, this is the best idea I could come up with:

def pirates_say_arrrrrrrrr(string)

	string.split("").each do|ch|
	 if ch == /r/i
	 	puts ch[+1]
	 end
	end

end

Can any one help me, please?

**Comment by nikeshashar** [comment]
@frazerWatson please re-open this issue in the PreCourse repo so you can get help :)
