### ISSUE TITLE
session 2:6

### ISSUE THREAD

**Issue by jaymuk** [makersacademy/ruby-kickstart#20]
Below is task 6 from session 2. My answer is written underneath - it doesn't pass all tests, and I can't seem to figure out why.

![screenshot 2015-03-14 13 04 04](https://cloud.githubusercontent.com/assets/7001177/6652838/0717fd2c-ca75-11e4-9cab-750d3aa85c5e.png)

Anyone know why this doesn't fully pass? What is wrong with my logic here?

Thanks!!

**Comment by maciejk77** [comment]
Link is broken?

**Comment by jaymuk** [comment]
updated!

**Comment by sanjsanj** [comment]
I did it a completely different way but shouldn't the `return true if` line only need to check if it divides into 1 with no remainder?  What's the `% 2` in there for?  Or maybe replace the 2 with itself?

**Comment by nikeshashar** [comment]
@jaymuk did you get this resolved?
