### ISSUE TITLE
2:12 - Fractions

### ISSUE THREAD

**Issue by Jeremy-Barrass** [makersacademy/ruby-kickstart#226]
I'm feeling very stuck, especially as the user AlexAvlontis who posted an issue about this challenge seemed to have a completely different challenge to the one I'm working on.

Anyway, my code keeps blowing up here:

```
def lowest
    puts "lowest method is running"
    puts "Calculating numerator gcd"
  	@numerator = self.gcd @numerator, @denominator
    puts "Numerator gcd calculation complete"
    puts @numerator # => produces a blank line
    puts "Calculating denominator gcd"
  	@denominator = self.gcd @denominator, @numerator 
    puts "Denominator calculation complete"
    puts "lowest method is complete"
    return @numerator, @denominator
end

def gcd(a,b) => # => Running from: puts "Calculating denominator gcd" : @denominator = self.gcd @denominator, @numerator 
    puts "gcd method is running"     
    return a if b == 0
    self.gcd(b, a%b) # => Throws the error: `%': nil can't be coerced into Float (TypeError)
    puts "gcd method is complete"
  end

```

I think I've misunderstood how fractions work, but it seems that the @numerator variable being passed to the gcd methods "b" parameter has nothng in it... which on further testing is indeed the case, as calling "puts" on it produces a blank line.  Let me go and revise basic mathematics, but can anyone shed light on why @numerator is being calculated to an empty variable by the code I'm currently using?

**Comment by Jeremy-Barrass** [comment]
So I looked up the maths and found out about the Euclid's Algorithm, which the method uses.  Having seen how I'm misapplying it, I've corrected that only to have another TypeError syntax error at the end of my lowest method instead.  It looks like the gcd method is still calculatngt a blank value...

**Comment by tcpickard94** [comment]
In your lowest method you need to call the class again. i.e Fraction.new(lnumerator, ldenominator)

**Comment by Jeremy-Barrass** [comment]
Thank you @tcpickard94 for commenting, I can see the point you make, but that does not resolve the error unfortunately.  Running the lowest method with the gcd method as follows:

```
 def lowest

    puts "lowest method is running"

    puts "Calculating gcd"

  	cgcd = gcd @numerator, @denominator

    puts "gcd calculation complete"

    puts cgcd

    lnumerator = @numerator / cgcd

    ldenominator = @denominator / cgcd

    puts "lowest method is complete"
    
    Fraction.new lnumerator, ldenominator
        
  end

 def gcd(a,b)
    puts "gcd method is running"
    puts a
    return a if b == 0
    self.gcd(b, a%b)
    puts "gcd method is complete"
  end

```

Produces the following output:

```
lowest method is running
Calculating gcd
gcd method is running
20.0
gcd method is running
60.0
gcd method is running
20.0
gcd method is complete
gcd method is complete
gcd calculation complete

/home/jeremy/Dropbox/Github/ruby-kickstart/session2/3-challenge/12_classes.rb:79:in `/': nil can't be coerced into Float (TypeError)
	from /home/jeremy/Dropbox/Github/ruby-kickstart/session2/3-challenge/12_classes.rb:79:in `lowest'
	from /home/jeremy/Dropbox/Github/ruby-kickstart/session2/3-challenge/12_classes.rb:95:in `<main>'

[Finished in 0.4s with exit code 1]

```

So for some reason, the a variable in gcd disappears in the 4th iteration.  But I can't figure out why.

**Comment by tcpickard94** [comment]
I think i've worked it out. It is to do with your gcd method. Remove the line (the puts statement) as this is returning when b != 0. Let me know if it works

**Comment by AlexAvlonitis** [comment]
hey @Jeremy-Barrass thanks for pointing it out my typo, i meant 2:13 :)

**Comment by Jeremy-Barrass** [comment]
@AlexAvlonitis: No problem, it did confuse me for a bit. :)

@tcpickard94: You were right, taking out all the puts from gcd fixed the return.  Hooray!  And thank you.  Funny how trying to debug made it worse.  Just the to_f method from the challenge returning 0 to fix now...

**Comment by tcpickard94** [comment]
@Jeremy-Barrass No problem. Glad you sorted it!

**Comment by Jeremy-Barrass** [comment]
All solved now, my thanks to the contributors here.
