### ISSUE TITLE
problem with rake / irb

### ISSUE THREAD

**Issue by HannaEb** [makersacademy/ruby-kickstart#262]
When I try to test my code with rake it keeps telling me my code is incorrect. I have tried copying the code from the solved folder and it's still not working so the problem is clearly not my code. It doesn't happen with every challenge, just a few of them. Also, most of the time rake rejects my code irb says it's fine (not always though). Does anyone have any idea what the problem could be? Please help as I can't keep working on the challenges until this is fixed :-(

**Comment by olmesm** [comment]
Post a few screen shots. Had no issues my side.

**Comment by anitacanita** [comment]
@HannaEb Can you please move this issue to the precourse? That way it gets posted on Slack and everyone can see it and help?
