### ISSUE TITLE
Session2. 3-challenges. 7_Array.rb - Rake not passing

### ISSUE THREAD

**Issue by sdawes** [makersacademy/ruby-kickstart#349]
Hi, I have completed the code for this challenge, and every example I pass to it, it seems to work, yet it fails the rake test and I can not interpret the reason. Any ideas? Thanks. 

```
def alternate_words(sentence)
	arr = sentence.split
	new_arr = []
	arr.map.with_index { |value, index| new_arr << value if index.even? }
	new_arr = new_arr.map { |element| element.tr("!@$#%^&*()-=_+[]:;,./<>?\|", '') }
end
```

**Comment by anitacanita** [comment]
@sdawes I recommend you move this issue to the [precourse repo](https://github.com/makersacademy/pre_course/issues), so it gets posted on Slack and everyone can see it!
