### ISSUE TITLE
arrays, logic and control, hashes, strings - Cheatsheets Missing

### ISSUE THREAD

**Issue by dregules** [makersacademy/ruby-kickstart#44]
FYI @spike01 - as I went through forking the repo and attempting some of the exercises... I realized that original repo (i.e. Josh Creek's one) contains a few more cheat sheets that are key for the initial sections. Particularly these are: 
arrays
logic and control
hashes
strings

See snapshot below to compare:

![image](https://cloud.githubusercontent.com/assets/1048262/8501688/a486aa8c-219f-11e5-8137-2e19ae644970.png)

![image](https://cloud.githubusercontent.com/assets/1048262/8501697/babf38be-219f-11e5-8f57-499bf65e108c.png)

**Comment by dregules** [comment]
@nikeshashar - keeping you in the loop of this one.

**Comment by nikeshashar** [comment]
@dregules it's fine to use those cheat sheets too and we will get them added to our repo in due course after reviewing them. 

On a side note, we have heavily customised our version or Ruby Kickstart to be tailored for the students and also to work with CI (continuous integration) so we can get you automated feedback on your code. 

Thanks for keeping me updated and good luck with Ruby week!

**Comment by dregules** [comment]
Excellent - thank you!
