### ISSUE TITLE
Rake 1:5 - Solution explanation

### ISSUE THREAD

**Issue by dregules** [makersacademy/ruby-kickstart#45]
Hi @nikeshashar - so, running Rake 1:5 does not fully validate my answer when all the 3 cases provided in the example comments I get them correctly. In all honesty, after several hours fighting, I also couldn't grasp the comments of the failures either (Screenshot provided).. So, which test-cases am I missing with my code below:

```ruby 
# Given a string, replace every instance of sad to happy
#
# add_more_ruby("The clowns were sad.")         # => "The clowns were happy."
# add_more_ruby("The sad dad said sad stuff.")  # => "The happy dad said happy stuff."
# add_more_ruby("Sad times are ahead!")         # => "Happy times are ahead!"

def add_more_ruby(string)
  string.gsub!(/sad/i, 'happy')
  print string.capitalize
  #string.gsub('sad', 'happy').gsub('Sad', 'Happy')  # => Solved code that does validate Rake 1:5  
end
```
![image](https://cloud.githubusercontent.com/assets/1048262/8507454/cf02e8d8-223b-11e5-935f-ce5317b2b339.png)

![image](https://cloud.githubusercontent.com/assets/1048262/8507465/6b5e52a8-223c-11e5-8bbd-bb691cb69eec.png)

Thank you in advance!!

**Comment by gerard-morera** [comment]
A a first try I would take print out of the statement. In rubys methods always last statement is returned

**Comment by gerard-morera** [comment]
The error is telling you that is expecting the return value "The clowns were happy." and instead getting `nil`
puts and print always return nil. They show it in the screen but this is a "side effect" but not the return value of the method.

**Comment by dregules** [comment]
Thanks for the comments @gerard-morera . Helped me to start looking at the failure comments after removing the `print`. Turns out, that there's not a way using regex in ruby that allows you to edit the replaced string's case. So, that's the error. My code would only work most cases, but make an error on "abc sad", for instance.

![image](https://cloud.githubusercontent.com/assets/1048262/8507636/8391814a-2243-11e5-93eb-9b8c23c03ad6.png)


Thanks again!

References: 
http://stackoverflow.com/questions/15627434/how-to-change-case-of-letters-in-string-using-regex-in-ruby
