### ISSUE TITLE
problem with rspec

### ISSUE THREAD

**Issue by blancopado** [makersacademy/ruby-kickstart#97]
Hi guys. I have installed rspec 3.2.0 and bundle. When I run rake 1:1 I get this error:

![captura de pantalla de 2015-10-04 11 56 11](https://cloud.githubusercontent.com/assets/9704761/10267284/f1cb10e8-6a8e-11e5-8118-4278c5fcc681.png)

![captura de pantalla de 2015-10-04 11 57 22](https://cloud.githubusercontent.com/assets/9704761/10267293/1a9e61c8-6a8f-11e5-974b-1503a6cb8cf4.png)

Does anybody knows how could I fix this?

**Comment by Mattia46** [comment]
@blancopado Can you try it to a different pc?

**Comment by blancopado** [comment]
don't have any other at the moment :/

**Comment by nikeshashar** [comment]
remove the repo and follow the instructions again. I've managed to get it going every time I've tried on a laptop

**Comment by blancopado** [comment]
Ok thanks, finally I fixed somehow.
